/// Local database
const localDb = 'poetic_logic_local_db';
const publishedDb = 'poetic_logic_published_db';

/// Inside remote DB
const publishedRemoteCollection = 'poetic_logic';

const settingsDb = 'poetic_logic_settings_db';
const settingsKey = 'settings';

const messageTimeChanges =
    'Time changes, goes on, the world still exists, so we understand in current circumstances. Few meaningful words to you. Generated by you.';

/// '28 There is neither Jew nor Gentile, neither slave nor free,
/// nor is there male and female, for you are all one in Christ Jesus.'
///	(Holy Bible, 1973: Galatians 3:28)
/// TODO: Examples, - are first published records.
const beAllOneJson = '''{
  "ifLogic" : "All is One, as Christ taught.",
  "quote" : {
    "text" : "28 There is neither Jew nor Gentile, neither slave nor free, nor is there male and female, for you are all one in Christ Jesus.",
    "title" : "Holy Bible",
    "year" :  "1973",
    "pages" : "3:28"
  },
  "thenLogic" : [
    "There are no likes or dislikes.",
    "Then it one lesson for all.",
    "Hide-and-seek - is the most fun game in the world.",
    "If I promise to one person, I promise to everybody.",
    "Then I will help you pay off your debts.",
    "Referencing this one should be enough.",
    "Competition is a fun.",
    "All thoughts is one thought."
  ],
  "user" : {
    "firstName": "Stepan",
    "lastName": "Zarubin",
    "mm": "11",
    "dd": "02"
  },
  "isPublished": true,
  "addedLogic" : [
    {
      "thenLogic" : [
        "Hyenas joke seriously, and lions are like flowers."
      ],
      "user": null
    },
    {
      "thenLogic" : [
        "I'm happy in any profession, in any place, and at any time. And by the way, not happy, too.",
        "If I eat you, then I eat myself.",
        "If I forget you...",
        "If I don't love you, I do not love...",
        "If I grow..."
      ],
      "user": null
    },
    {
      "thenLogic" : [
        "If I sick...",
        "I worry, if I don't understand something.",
        "If I relax...",
        "I will try to forget who I am. And I will try to forget who I am."
      ],
      "user": {
        "firstName": "Stepan",
        "lastName": "Zarubin",
        "mm": "11",
        "dd": "02"
      }
    },
    {
      "thenLogic" : [
        "php is not worse then c++. And even more - php 3 is not worse then php 7.",
        "user never disconnected",
        "I see this in international relations between countries.",
        "There is only one software program in the world"
      ],
      "user": null
    }
  ]
}
''';

const examples = '''

''';
