// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiEmMdADJkGBaU7G237yN6w9dAvyXxg-g',
    appId: '1:875153840113:web:b9e8d7f9d4a80aa56d5650',
    messagingSenderId: '875153840113',
    projectId: 'poetic-logic-b69a1',
    authDomain: 'poetic-logic-b69a1.firebaseapp.com',
    databaseURL: 'https://poetic-logic-b69a1-default-rtdb.firebaseio.com',
    storageBucket: 'poetic-logic-b69a1.appspot.com',
    measurementId: 'G-XV8SYX18ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9pYOmBFFz4mVTEzWyFewKVx82Eeamchw',
    appId: '1:875153840113:android:2e6ca1c1263c528b6d5650',
    messagingSenderId: '875153840113',
    projectId: 'poetic-logic-b69a1',
    databaseURL: 'https://poetic-logic-b69a1-default-rtdb.firebaseio.com',
    storageBucket: 'poetic-logic-b69a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjUDRJyb7PxUvcqqwL3IB9DwUoLfjhrAA',
    appId: '1:875153840113:ios:688c00b6ba22cb436d5650',
    messagingSenderId: '875153840113',
    projectId: 'poetic-logic-b69a1',
    databaseURL: 'https://poetic-logic-b69a1-default-rtdb.firebaseio.com',
    storageBucket: 'poetic-logic-b69a1.appspot.com',
    iosClientId: '875153840113-hksfi1tcini42ctp0nae4e93u2jl4bn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.poeticLogic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjUDRJyb7PxUvcqqwL3IB9DwUoLfjhrAA',
    appId: '1:875153840113:ios:688c00b6ba22cb436d5650',
    messagingSenderId: '875153840113',
    projectId: 'poetic-logic-b69a1',
    databaseURL: 'https://poetic-logic-b69a1-default-rtdb.firebaseio.com',
    storageBucket: 'poetic-logic-b69a1.appspot.com',
    iosClientId: '875153840113-hksfi1tcini42ctp0nae4e93u2jl4bn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.poeticLogic',
  );
}
